version: '2'
services:
    mosaic-app:
        image: mosaic
        external_links:
            - mosaic-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mosaic?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mosaic-mysql:
        extends:
            file: mysql.yml
            service: mosaic-mysql
